/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/~__root'
import { Route as IndexRouteImport } from './routes/~index'
import { Route as ChangelogRouteImport } from './routes/~changelog'
import { Route as McpRouteImport } from './routes/~mcp'
import { Route as RepositoriesRepositoryIdAllOwnersRouteImport } from './routes/~repositories/~$repositoryId/~all-owners'
import { Route as RepositoriesRepositoryIdCodeownersRouteImport } from './routes/~repositories/~$repositoryId/~codeowners'
import { Route as RepositoriesRepositoryIdFileOwnerRouteImport } from './routes/~repositories/~$repositoryId/~file-owner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRepositoryIdAllOwnersRoute =
  RepositoriesRepositoryIdAllOwnersRouteImport.update({
    id: '/repositories/$repositoryId/all-owners',
    path: '/repositories/$repositoryId/all-owners',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoriesRepositoryIdCodeownersRoute =
  RepositoriesRepositoryIdCodeownersRouteImport.update({
    id: '/repositories/$repositoryId/codeowners',
    path: '/repositories/$repositoryId/codeowners',
    getParentRoute: () => rootRouteImport,
  } as any)
const RepositoriesRepositoryIdFileOwnerRoute =
  RepositoriesRepositoryIdFileOwnerRouteImport.update({
    id: '/repositories/$repositoryId/file-owner',
    path: '/repositories/$repositoryId/file-owner',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/mcp': typeof McpRoute
  '/repositories/$repositoryId/all-owners': typeof RepositoriesRepositoryIdAllOwnersRoute
  '/repositories/$repositoryId/codeowners': typeof RepositoriesRepositoryIdCodeownersRoute
  '/repositories/$repositoryId/file-owner': typeof RepositoriesRepositoryIdFileOwnerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/mcp': typeof McpRoute
  '/repositories/$repositoryId/all-owners': typeof RepositoriesRepositoryIdAllOwnersRoute
  '/repositories/$repositoryId/codeowners': typeof RepositoriesRepositoryIdCodeownersRoute
  '/repositories/$repositoryId/file-owner': typeof RepositoriesRepositoryIdFileOwnerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/mcp': typeof McpRoute
  '/repositories/$repositoryId/all-owners': typeof RepositoriesRepositoryIdAllOwnersRoute
  '/repositories/$repositoryId/codeowners': typeof RepositoriesRepositoryIdCodeownersRoute
  '/repositories/$repositoryId/file-owner': typeof RepositoriesRepositoryIdFileOwnerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/mcp'
    | '/repositories/$repositoryId/all-owners'
    | '/repositories/$repositoryId/codeowners'
    | '/repositories/$repositoryId/file-owner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/mcp'
    | '/repositories/$repositoryId/all-owners'
    | '/repositories/$repositoryId/codeowners'
    | '/repositories/$repositoryId/file-owner'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/mcp'
    | '/repositories/$repositoryId/all-owners'
    | '/repositories/$repositoryId/codeowners'
    | '/repositories/$repositoryId/file-owner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  McpRoute: typeof McpRoute
  RepositoriesRepositoryIdAllOwnersRoute: typeof RepositoriesRepositoryIdAllOwnersRoute
  RepositoriesRepositoryIdCodeownersRoute: typeof RepositoriesRepositoryIdCodeownersRoute
  RepositoriesRepositoryIdFileOwnerRoute: typeof RepositoriesRepositoryIdFileOwnerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId/all-owners': {
      id: '/repositories/$repositoryId/all-owners'
      path: '/repositories/$repositoryId/all-owners'
      fullPath: '/repositories/$repositoryId/all-owners'
      preLoaderRoute: typeof RepositoriesRepositoryIdAllOwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId/codeowners': {
      id: '/repositories/$repositoryId/codeowners'
      path: '/repositories/$repositoryId/codeowners'
      fullPath: '/repositories/$repositoryId/codeowners'
      preLoaderRoute: typeof RepositoriesRepositoryIdCodeownersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories/$repositoryId/file-owner': {
      id: '/repositories/$repositoryId/file-owner'
      path: '/repositories/$repositoryId/file-owner'
      fullPath: '/repositories/$repositoryId/file-owner'
      preLoaderRoute: typeof RepositoriesRepositoryIdFileOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  McpRoute: McpRoute,
  RepositoriesRepositoryIdAllOwnersRoute:
    RepositoriesRepositoryIdAllOwnersRoute,
  RepositoriesRepositoryIdCodeownersRoute:
    RepositoriesRepositoryIdCodeownersRoute,
  RepositoriesRepositoryIdFileOwnerRoute:
    RepositoriesRepositoryIdFileOwnerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
